[template.environment]
  GQL_HOST = "evelatus.lionssolution.com"
  NUXT_IMAGE_DOMAINS = "evelatus.lionssolution.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://evelatus.lionssolution.com/wp-content/uploads/.*"]
