[template.environment]
  GQL_HOST = "headleswoo.lionssolution.com"
  NUXT_IMAGE_DOMAINS = "headleswoo.lionssolution.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://headleswoo.lionssolution.com/wp-content/uploads/.*"]
